name: code_sprout
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^4.2.0
  firebase_auth: ^6.1.1
  cloud_firestore: ^6.0.3
  flutter_secure_storage: ^9.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/icons/
    - assets/images/icons/languages/
    - assets/images/icons/module_items/
    - assets/images/icons/nav_buttons/
    - assets/images/icons/on_cards/
    - assets/images/icons/sprout_items/
    - assets/images/icons/sprout_items/crop_items/
    - assets/images/icons/sprout_items/farm_items/
    - assets/images/icons/sprout_items/miscellaneous/
    - assets/images/icons/sprout_items/seed_items/
    - assets/references/
    - assets/schemas/
    - assets/schemas/courses/
    - assets/schemas/courses/cpp/
    - assets/schemas/courses/cpp/advanced/
    - assets/schemas/courses/cpp/advanced/chapter_1/
    - assets/schemas/courses/cpp/beginner/
    - assets/schemas/courses/cpp/beginner/chapter_1/
    - assets/schemas/courses/cpp/beginner/chapter_2/
    - assets/schemas/courses/cpp/intermediate/
    - assets/schemas/courses/cpp/intermediate/chapter_1/
    - assets/schemas/courses/csharp/
    - assets/schemas/courses/java/
    - assets/schemas/courses/javascript/
    - assets/schemas/courses/javascript/beginner/
    - assets/schemas/courses/javascript/beginner/chapter_1/
    - assets/schemas/courses/python/
    - assets/schemas/courses/python/beginner/
    - assets/schemas/courses/python/beginner/chapter_1/
    - assets/schemas/researches/
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Thin.ttf
          weight: 100
        - asset: fonts/Poppins-ExtraLight.ttf
          weight: 200
        - asset: fonts/Poppins-Light.ttf
          weight: 300
        - asset: fonts/Poppins-Regular.ttf
          weight: 400
        - asset: fonts/Poppins-Medium.ttf
          weight: 500
        - asset: fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: fonts/Poppins-Bold.ttf
          weight: 700
        - asset: fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: fonts/Poppins-Black.ttf
          weight: 900
